// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkxyhkljvlndkxmlbhfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZreHloa2xqdmxuZGt4bWxiaGZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MTg0MzksImV4cCI6MjA2OTQ5NDQzOX0.MWQTcNHRknDULpZyOdX846lUL6UJ2uQ3QuK9n3R9cjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});